import type { SurveyConfig, SurveyQuestion } from "@/lib/survey-types";

const likert = (
  id: string,
  label: string,
  helperText: string,
  required = true,
  extra?: Partial<SurveyQuestion>,
): SurveyQuestion => ({
  id,
  type: "likert",
  required,
  label,
  helperText,
  scaleLabels: ["かなり低い", "かなり高い"],
  ...extra,
});

const textarea = (
  id: string,
  label: string,
  helperText: string,
  required = false,
  placeholder = "抽象的でも雑でも大丈夫です。遠慮せず書いてください。",
  rows = 5,
): SurveyQuestion => ({
  id,
  type: "textarea",
  required,
  label,
  helperText,
  placeholder,
  rows,
});

const shortText = (
  id: string,
  label: string,
  helperText: string,
  required = false,
  placeholder = "短くて大丈夫です。",
): SurveyQuestion => ({
  id,
  type: "shortText",
  required,
  label,
  helperText,
  placeholder,
});

export const surveySections: SurveyConfig = [
  {
    id: "section-0",
    key: "intro",
    title: "導入",
    sortOrder: 0,
    estimatedMinutes: "1分",
    description: [
      "このアンケートは褒めるためではなく、UniDropを改善するためのものです。",
      "微妙だった点、ダサいと感じた点、不安だった点ほど価値があります。友達として気を遣う必要はありません。",
      "率直なフィードバックが、次の改善にそのままつながります。",
    ],
    questions: [
      {
        id: "honest_feedback_consent",
        type: "checkbox",
        required: true,
        label: "率直なフィードバックを行うことに同意する",
        helperText: "褒める必要はありません。気になった違和感ほど歓迎です。",
        options: [{ value: "agreed", label: "同意する" }],
        minSelections: 1,
        maxSelections: 1,
      },
      {
        id: "no_personal_info_consent",
        type: "checkbox",
        required: true,
        label: "他テスターや相手の個人情報は書かない",
        helperText: "個人名、連絡先、学籍番号などは記入しないでください。",
        options: [{ value: "agreed", label: "同意する" }],
        minSelections: 1,
        maxSelections: 1,
      },
    ],
  },
  {
    id: "section-1",
    key: "basic_info",
    title: "基本情報",
    sortOrder: 1,
    estimatedMinutes: "2分",
    description: [
      "回答の傾向を大づかみで見るための項目です。個人が特定される用途には使いません。",
    ],
    questions: [
      {
        id: "grade",
        type: "radio",
        required: true,
        label: "学年",
        helperText: "最も近いものを選んでください。",
        options: [
          { value: "b1", label: "学部1年" },
          { value: "b2", label: "学部2年" },
          { value: "b3", label: "学部3年" },
          { value: "b4", label: "学部4年" },
          { value: "m1", label: "修士1年" },
          { value: "m2", label: "修士2年" },
          { value: "d1_plus", label: "博士課程" },
          { value: "other", label: "その他" },
        ],
      },
      shortText(
        "affiliation",
        "所属",
        "学類・研究科・サークルなど、ざっくりで構いません。",
        true,
        "例: 情報学群 / 体育専門学群 / システム情報工学研究群",
      ),
      {
        id: "gender",
        type: "radio",
        required: false,
        label: "性別",
        helperText: "任意回答です。",
        options: [
          { value: "woman", label: "女性" },
          { value: "man", label: "男性" },
          { value: "non_binary", label: "ノンバイナリー" },
          { value: "prefer_not_to_say", label: "回答しない" },
        ],
      },
      {
        id: "matching_app_experience",
        type: "radio",
        required: true,
        label: "普段の類似サービス利用経験",
        helperText: "ここでは一般的な恋愛系・つながり系サービス全般を含みます。",
        options: [
          { value: "used", label: "使ったことがある" },
          { value: "installed_but_rarely_used", label: "入れたことはあるがほぼ使っていない" },
          { value: "never_used", label: "使ったことがない" },
          { value: "actively_avoid", label: "使いたくない派" },
        ],
      },
      {
        id: "participation_reasons",
        type: "checkbox",
        required: true,
        label: "UniDrop参加のきっかけ",
        helperText: "当てはまるものをすべて選んでください。",
        options: [
          { value: "invited_by_friend", label: "友達に誘われた" },
          { value: "looked_interesting", label: "面白そうだった" },
          { value: "interested_in_diagnosis", label: "診断に興味があった" },
          { value: "liked_tsukuba_only", label: "筑波限定に惹かれた" },
          { value: "connection_purpose", label: "恋愛・つながり目的" },
          { value: "other", label: "その他" },
        ],
        minSelections: 1,
      },
    ],
  },
  {
    id: "section-2",
    key: "pre_signup",
    title: "登録前の印象",
    sortOrder: 2,
    estimatedMinutes: "3分",
    description: [
      "入口の時点で何が伝わっていて、何が警戒につながったのかを知りたいセクションです。",
    ],
    questions: [
      textarea(
        "service_guess_before_signup",
        "登録前、UniDropを何のサービスだと思っていたか",
        "第一印象ベースで大丈夫です。",
        true,
      ),
      {
        id: "impression_before_signup",
        type: "radio",
        required: true,
        label: "登録前の印象",
        helperText: "最も近いものを選んでください。",
        options: [
          { value: "interesting_diagnosis", label: "面白そうな価値観診断" },
          { value: "campus_connection_service", label: "筑波大向けの新しいつながりサービス" },
          { value: "basically_matching_app", label: "ほぼマッチングアプリ" },
          { value: "unclear", label: "よくわからなかった" },
          { value: "felt_suspicious", label: "少し怪しいと感じた" },
        ],
      },
      {
        id: "concerns_before_signup",
        type: "checkbox",
        required: true,
        label: "登録前に不安だったこと",
        helperText: "複数選択できます。",
        options: [
          { value: "noticed_by_acquaintances", label: "知り合いにバレそう" },
          { value: "embarrassing", label: "恥ずかしい" },
          { value: "felt_like_dating_service", label: "出会い系っぽく感じた" },
          { value: "personal_data", label: "個人情報が不安" },
          { value: "too_long_diagnosis", label: "診断が長そう" },
          { value: "awkward_after_match", label: "つながっても気まずそう" },
          { value: "uncertain_user_base", label: "本当に人がいるのか不安" },
          { value: "none", label: "特になし" },
          { value: "other", label: "その他" },
        ],
        minSelections: 1,
      },
      {
        id: "signup_drivers",
        type: "checkbox",
        required: true,
        label: "登録の後押しになった要素",
        helperText: "最大3つまで選べます。",
        options: [
          { value: "tsukuba_only", label: "筑波大限定" },
          { value: "no_face_photo", label: "顔写真なし" },
          { value: "values_diagnosis", label: "価値観診断" },
          { value: "one_drop_per_week", label: "毎週1人だけ届く" },
          { value: "friends_were_using", label: "友達がやっていた" },
          { value: "other", label: "その他" },
        ],
        minSelections: 1,
        maxSelections: 3,
      },
      textarea(
        "biggest_hangup_before_signup",
        "登録前に一番ひっかかった点",
        "些細な引っかかりでも構いません。",
      ),
    ],
  },
  {
    id: "section-3",
    key: "onboarding",
    title: "登録体験",
    sortOrder: 3,
    estimatedMinutes: "3分",
    description: [
      "登録動線そのものの摩擦や、説明不足だった箇所を把握するためのセクションです。",
    ],
    questions: [
      likert("signup_ease", "登録のしやすさ", "1がかなりしづらい、5がかなりしやすい。"),
      {
        id: "signup_stumbling_points",
        type: "checkbox",
        required: true,
        label: "つまずいた箇所",
        helperText: "該当するものを選んでください。",
        options: [
          { value: "email_verification", label: "メール認証" },
          { value: "password_setup", label: "パスワード設定" },
          { value: "field_meaning", label: "入力項目の意味" },
          { value: "screen_transition", label: "画面遷移" },
          { value: "none", label: "特になし" },
          { value: "other", label: "その他" },
        ],
        minSelections: 1,
      },
      likert(
        "concept_clarity",
        "初見でサービス内容が理解しやすかったか",
        "1がかなりわかりにくい、5がかなりわかりやすい。",
      ),
      textarea(
        "confusing_points",
        "わかりづらかった点",
        "言葉、構成、UI、流れのどれでも構いません。",
      ),
      textarea(
        "missing_explanation",
        "サービス説明で足りなかったこと",
        "登録前後のどちらの説明でも大丈夫です。",
      ),
    ],
  },
  {
    id: "section-4",
    key: "diagnosis",
    title: "診断体験",
    sortOrder: 4,
    estimatedMinutes: "4分",
    description: [
      "55問というボリュームが体験価値として成立しているか、どこで負荷が上がるかを知りたいです。",
    ],
    questions: [
      likert("diagnosis_satisfaction", "診断全体の満足度", "1がかなり低い、5がかなり高い。"),
      {
        id: "diagnosis_length_impression",
        type: "radio",
        required: true,
        label: "55問の長さの印象",
        helperText: "体感に近いものを選んでください。",
        options: [
          { value: "very_long", label: "かなり長い" },
          { value: "somewhat_long", label: "やや長い" },
          { value: "just_right", label: "ちょうどいい" },
          { value: "somewhat_short", label: "やや短い" },
          { value: "short", label: "短い" },
        ],
      },
      {
        id: "diagnosis_fatigue_point",
        type: "radio",
        required: true,
        label: "一番だれた箇所",
        helperText: "最も近いものを選んでください。",
        options: [
          { value: "profile_setup", label: "最初のプロフィール入力" },
          { value: "early_questions", label: "診断前半" },
          { value: "middle_questions", label: "診断中盤" },
          { value: "late_questions", label: "診断後半" },
          { value: "profile_finish", label: "プロフィール仕上げ" },
          { value: "none", label: "特になし" },
        ],
      },
      likert(
        "diagnosis_intent_confusion",
        "質問の意図がわからないと感じたか",
        "1が全く感じなかった、5がかなり感じた。",
      ),
      textarea(
        "memorable_or_weird_questions",
        "印象に残った質問 / 変だと思った質問",
        "良かった質問でも、違和感があった質問でも構いません。",
      ),
      likert(
        "diagnosis_validity",
        "相性を見る材料として納得感があったか",
        "1がかなり低い、5がかなり高い。",
      ),
      likert(
        "diagnosis_fun_over_hassle",
        "面倒さより面白さが勝ったか",
        "1が面倒さが勝った、5が面白さが勝った。",
      ),
      {
        id: "save_resume_ease",
        type: "radio",
        required: true,
        label: "途中保存・再開のしやすさ",
        helperText: "未使用ならその項目を選んでください。",
        options: [
          { value: "1", label: "1" },
          { value: "2", label: "2" },
          { value: "3", label: "3" },
          { value: "4", label: "4" },
          { value: "5", label: "5" },
          { value: "not_used", label: "未使用" },
        ],
      },
      textarea(
        "diagnosis_improve_one",
        "診断体験で一番直してほしい点",
        "1つに絞れなくても大丈夫です。",
      ),
    ],
  },
  {
    id: "section-5",
    key: "drop",
    title: "Drop体験",
    sortOrder: 5,
    estimatedMinutes: "4分",
    description: [
      "Drop を見た瞬間の感情、相性の納得感、顔写真なし設計の受け止められ方を見ます。",
    ],
    questions: [
      {
        id: "drop_first_impression",
        type: "radio",
        required: true,
        label: "Dropが届いた時の第一印象",
        helperText: "最初に近かった感情を選んでください。",
        options: [
          { value: "wow_interesting", label: "おお、面白い" },
          { value: "slightly_excited", label: "ちょっとワクワクした" },
          { value: "neutral", label: "ふーん、という感じ" },
          { value: "not_compelling", label: "正直あまり刺さらなかった" },
          { value: "unclear", label: "よくわからなかった" },
        ],
      },
      likert("compatibility_score_trust", "相性スコアの納得感", "1がかなり低い、5がかなり高い。"),
      likert("reasons_trust", "3つの相性理由の納得感", "1がかなり低い、5がかなり高い。"),
      likert(
        "want_to_talk",
        "届いた相手に少し話してみたいと思えたか",
        "1が全く思えなかった、5がかなり思えた。",
      ),
      {
        id: "weekly_one_drop_impression",
        type: "radio",
        required: true,
        label: "毎週1人だけ届く仕組みへの印象",
        helperText: "直感に近いものを選んでください。",
        options: [
          { value: "just_right", label: "ちょうどいい" },
          { value: "low_but_valid", label: "少ないけどコンセプトとしてあり" },
          { value: "too_few", label: "物足りない" },
          { value: "want_more_control", label: "もっと自分で選びたい" },
          { value: "unclear", label: "よくわからない" },
        ],
      },
      likert(
        "no_face_photo_interest",
        "顔写真なしでも興味を持てたか",
        "1がかなり持てなかった、5がかなり持てた。",
      ),
      textarea("drop_good_points", "Drop体験の良かった点", "良いと思った理由を自由に書いてください。"),
      textarea(
        "drop_weak_points",
        "Drop体験の微妙だった点 / 冷めた点",
        "冷めた瞬間や、引っかかった要素を書いてください。",
      ),
      shortText(
        "drop_one_line",
        "Drop画面を見た時の率直な一言",
        "一言で大丈夫です。",
        false,
        "例: 思ったより静か / 期待したより地味 / これは話してみたい",
      ),
    ],
  },
  {
    id: "section-6",
    key: "chat",
    title: "チャット体験",
    sortOrder: 6,
    estimatedMinutes: "3分",
    description: [
      "最初の1通が送りやすいか、気まずさの正体が UI なのか心理なのかを見分けます。",
    ],
    questions: [
      likert("first_message_ease", "最初の1通の送りやすさ", "1がかなり送りにくい、5がかなり送りやすい。"),
      {
        id: "first_message_hesitation",
        type: "radio",
        required: true,
        label: "最初の1通を送るまで迷ったか",
        helperText: "最も近いものを選んでください。",
        options: [
          { value: "a_lot", label: "かなり迷った" },
          { value: "a_bit", label: "少し迷った" },
          { value: "not_much", label: "あまり迷わなかった" },
          { value: "none", label: "全く迷わなかった" },
        ],
      },
      likert(
        "first_message_confusion",
        "何を送ればいいかわからなかったか",
        "1が全くわからなかったわけではない、5がかなりわからなかった。",
      ),
      {
        id: "chat_atmosphere",
        type: "radio",
        required: true,
        label: "チャットの雰囲気",
        helperText: "最も近かったものを選んでください。",
        options: [
          { value: "more_natural_than_expected", label: "思ったより自然だった" },
          { value: "slightly_awkward", label: "少し気まずかった" },
          { value: "very_awkward", label: "かなり気まずかった" },
          { value: "depends_on_person", label: "相手次第だと思った" },
          { value: "ui_hard_to_use", label: "UI的にやりにくかった" },
        ],
      },
      textarea(
        "chat_barriers",
        "チャットを始めにくくした理由",
        "言葉が出ない、温度感がわからない、UI が硬い、など何でも構いません。",
      ),
      textarea(
        "chat_enablers",
        "始めやすくした要素",
        "逆に、送りやすくしていた要素があれば書いてください。",
      ),
      {
        id: "template_interest",
        type: "radio",
        required: true,
        label: "会話きっかけ提案や初手テンプレがあれば使いたいか",
        helperText: "必要度に近いものを選んでください。",
        options: [
          { value: "strongly_want", label: "かなり使いたい" },
          { value: "would_use", label: "あれば使う" },
          { value: "neutral", label: "どちらでもよい" },
          { value: "unnecessary", label: "なくてよい" },
        ],
      },
      textarea(
        "chat_improve_one",
        "チャット機能で一番改善してほしい点",
        "仕様でも UI でも心理的な導線でも構いません。",
      ),
    ],
  },
  {
    id: "section-7",
    key: "safety",
    title: "安心感",
    sortOrder: 7,
    estimatedMinutes: "3分",
    description: [
      "匿名性の設計が安心につながっているか、それとも逆に不安を増やしているかを確認します。",
    ],
    questions: [
      likert(
        "tsukuba_only_safety",
        "筑波大限定であることの安心感",
        "1が全く安心につながらない、5がかなり安心につながる。",
      ),
      likert(
        "optional_photo_safety",
        "顔写真任意の安心感",
        "1が全く安心につながらない、5がかなり安心につながる。",
      ),
      likert(
        "nickname_safety",
        "ニックネーム制の安心感",
        "1が全く安心につながらない、5がかなり安心につながる。",
      ),
      likert(
        "blocklist_expectation",
        "除外リスト機能があれば安心だと思うか",
        "1が不要、5がかなり必要。",
      ),
      {
        id: "anxieties",
        type: "checkbox",
        required: true,
        label: "不安を感じた点",
        helperText: "複数選択できます。",
        options: [
          { value: "could_match_acquaintance", label: "知り合いと当たりそう" },
          { value: "too_anonymous", label: "身元がわからなすぎる" },
          { value: "worry_about_bad_actors", label: "変な人がいないか不安" },
          { value: "data_handling", label: "個人情報の扱いが不安" },
          { value: "screenshot_risk", label: "スクショされそう" },
          { value: "none", label: "特になし" },
          { value: "other", label: "その他" },
        ],
        minSelections: 1,
      },
      textarea(
        "what_needed_for_safety",
        "もっと安心できるように必要なこと",
        "ルール、説明、機能、表現のどれでも構いません。",
      ),
    ],
  },
  {
    id: "section-8",
    key: "overall",
    title: "全体評価",
    sortOrder: 8,
    estimatedMinutes: "3分",
    description: [
      "総合評価だけでなく、友達にどう説明されるかでプロダクトのポジションを見ます。",
    ],
    questions: [
      {
        id: "nps",
        type: "nps",
        required: true,
        label: "友達に勧めたいか",
        helperText: "0 が全く勧めたくない、10 がかなり勧めたいです。",
        options: [],
      },
      textarea("nps_reason", "その点数の理由", "点数をつけた理由を率直に書いてください。", true),
      textarea(
        "describe_to_friend",
        "友達に説明するとしたら何と言うか",
        "実際にそのまま送るつもりで書いてみてください。",
        true,
      ),
      {
        id: "closest_category",
        type: "radio",
        required: true,
        label: "UniDropは何に一番近いと感じたか",
        helperText: "現時点の認識に近いものを選んでください。",
        options: [
          { value: "matching_app", label: "マッチングアプリ" },
          { value: "romantic_values_service", label: "恋愛寄りの価値観診断サービス" },
          { value: "campus_connection_service", label: "筑波限定の新しいつながりサービス" },
          { value: "diagnostic_content", label: "診断コンテンツ" },
          { value: "still_unclear", label: "まだよくわからない" },
        ],
      },
      shortText("best_part", "一番良いところを一言で", "短くて構いません。", true, "例: 入口の静けさ"),
      shortText("weakest_part", "一番弱いところを一言で", "短くて構いません。", true, "例: 初手の気まずさ"),
    ],
  },
  {
    id: "section-9",
    key: "blunt_feedback",
    title: "本音回収",
    sortOrder: 9,
    estimatedMinutes: "4分",
    description: [
      "最後は遠慮なしでお願いします。きれいな意見より、本音の違和感を取りにいくセクションです。",
    ],
    questions: [
      textarea(
        "hidden_core_discomfort",
        "運営が気づいていなさそうな根本的違和感",
        "見落としていそうなものほど歓迎です。",
        true,
      ),
      textarea(
        "why_not_spread",
        "このままだと広がらなそうだと思う理由",
        "利用者の心理、見え方、体験設計のどれでも構いません。",
        true,
      ),
      textarea(
        "one_fix_to_improve",
        "ここを直せば一気によくなると思う点を1つ",
        "優先度が高いと感じるものを挙げてください。",
        true,
      ),
      textarea(
        "uncool_or_unclear_points",
        "優しさなしで言うダサい点 / 痛い点 / 伝わりづらい点",
        "言いづらいことほど助かります。",
        true,
      ),
      textarea(
        "next_week_priority",
        "自分が運営だったら次の1週間で何を直すか",
        "具体的でも雑でも構いません。",
        true,
      ),
    ],
  },
];

export const surveySectionMap = Object.fromEntries(
  surveySections.map((section) => [section.key, section]),
);

export const surveyQuestions = surveySections.flatMap((section) => section.questions);

export const surveyQuestionMap = Object.fromEntries(
  surveyQuestions.map((question) => [question.id, question]),
);

export const surveyQuestionLabels = Object.fromEntries(
  surveyQuestions.map((question) => [question.id, question.label]),
);
